monolog:
    handlers:
        console:
            type: console
            process_psr_3_messages: false
            channels: [ '!event', '!doctrine', '!console' ]
            verbosity_levels:
               VERBOSITY_NORMAL: NOTICE

        rotating_file:
            type:  rotating_file
            path: "%kernel.logs_dir%/app.log"
            level: notice
            max_files: 10

