services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Domain/'
      - '../src/Tests/'
      - '../src/Kernel.php'
